name: Update version according to git flow 
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Update version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: npm i
      
      - name: Update version
        run: node scripts/semver

      - name: Save version
        uses: EndBug/add-and-commit@v4
        with:
          add: 'package.json'
          message: 'Update version'
        id: version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.version.outputs }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false