name: Update version according to git flow 
on:
  push:
    branches:
      - feature/*

jobs:
  build:
    name: Update version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      
      - name: Update version
        run: node scripts/semver