name: Update version according to git flow 
on:
  push:
    branches:
      - feature/*

jobs:
  build:
    name: Update version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: npm i
      
      - name: Update version
        run: node scripts/semver

      - name: Save version
      - uses: EndBug/add-and-commit@v4 # You can change this to use a specific version
        with:
          add: 'package.json'
          message: 'Update version'
        env:
          # This is necessary in order to push a commit to the repo
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged